const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={insight:Number(localStorage.getItem('path-insight'))||120,trust:Number(localStorage.getItem('path-trust'))||6,focus:false,clues:new Set(JSON.parse(localStorage.getItem('path-fp-clues')||'[]')),dialogueStep:0,lookX:0,lookY:0};
const clueData={books:{title:'A copied folio',copy:'The margin names a transmitter, but gives no source for the attribution. A useful lead—not proof.'},arch:{title:'A maker’s mark',copy:'The same geometric sign appears on the courier’s route. Context can connect evidence without deciding authenticity.'},pottery:{title:'The potter’s seal',copy:'A date places the object after one claimed transmitter had died. Chronology can expose a broken chain.'}};
const dialogue=[
  {text:'You came for the saying carried through the market. Tell me: if its words sound wise, is that enough to attribute it to Imam al-Sadiq?',choices:[['Yes—the benefit proves its origin.','wrong'],['No. We should trace its source and chain.','right'],['If many people repeat it, it becomes reliable.','wrong']]},
  {text:'Good. A beautiful meaning may still be misattributed. Examine the stall, the courtyard mark, and the potter’s seal. Each clue teaches a different part of verification.',choices:[['I will investigate before I judge.','continue']]},
  {text:'You found the pieces. The folio names a transmitter, the seal tests chronology, and the route gives context. What should we do next?',choices:[['Declare the report authentic ourselves.','wrong2'],['Record the evidence and consult qualified scholarship.','complete'],['Discard every version of the report.','wrong2']]},
  {text:'That is the discipline of knowledge: verify carefully, name uncertainty honestly, and do not place words on the Imams without evidence.',choices:[['Close the casebook.','end']]}
];
function sync(){ $('#insight').textContent=state.insight;$('#trust').textContent=state.trust;$('#evidenceCount').textContent=`Evidence ${state.clues.size} / 3`;$$('.evidence-row i').forEach((x,i)=>x.classList.toggle('found',i<state.clues.size));$$('.clue').forEach(x=>x.classList.toggle('found',state.clues.has(x.dataset.clue)));if(state.clues.size===3){state.dialogueStep=Math.max(state.dialogueStep,2);$('#objectiveText').textContent=state.dialogueStep>=3?'Sequence complete':'Return to Ustadha Maryam'}}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2300)}
function setFocus(on=!state.focus){state.focus=on;$('#game').classList.toggle('focused',on);$('#focusBtn').setAttribute('aria-pressed',String(on));toast(on?'Scholar’s focus reveals points of evidence':'Scholar’s focus closed')}
function openDialogue(){state.focus=false;$('#game').classList.remove('focused');$('#focusBtn').setAttribute('aria-pressed','false');$('#dialogue').classList.remove('hidden');renderDialogue()}
function closeDialogue(){$('#dialogue').classList.add('hidden')}
function renderDialogue(){const d=dialogue[state.dialogueStep];$('#dialogueText').textContent=d.text;$('#dialogueStep').textContent=`Conversation · ${state.dialogueStep+1} / ${dialogue.length}`;$('#choices').innerHTML='';d.choices.forEach(([label,action])=>{const b=document.createElement('button');b.textContent=label;b.onclick=()=>choose(action);$('#choices').appendChild(b)})}
function choose(action){if(action==='wrong'){state.trust=Math.max(0,state.trust-1);toast('Trust −1 · Attribution needs evidence');state.dialogueStep=1}else if(action==='right'){state.insight+=20;state.trust+=1;toast('Insight +20 · Trust +1');state.dialogueStep=1}else if(action==='continue'){closeDialogue();$('#objectiveText').textContent='Use Scholar’s Focus to find 3 clues';setFocus(true);save();return}else if(action==='wrong2'){toast('A learner records evidence; a scholar assesses it');state.dialogueStep=3}else if(action==='complete'){state.insight+=40;state.trust+=1;toast('Case resolved · Insight +40 · Trust +1');state.dialogueStep=3;$('#objectiveText').textContent='Sequence complete'}else{closeDialogue();openSheet('journal');save();return}save();sync();renderDialogue()}
function save(){localStorage.setItem('path-insight',state.insight);localStorage.setItem('path-trust',state.trust);localStorage.setItem('path-fp-clues',JSON.stringify([...state.clues]))}
function investigate(key){if(state.clues.has(key)){toast('Already recorded in the casebook');return}state.clues.add(key);state.insight+=10;save();sync();toast(`${clueData[key].title} recorded · Insight +10`)}
function openSheet(type){const source=type==='sources';$('#sheetEyebrow').textContent=source?'Method & source notes':'Investigation record';$('#sheetTitle').textContent=source?'Hadith verification':'The Unbroken Chain';$('#sheetBody').innerHTML=source?`<p class="sheet-intro">This story teaches source literacy, not independent hadith grading or religious rulings.</p><div class="record"><span>Principle</span><strong>Examine sanad and matn</strong><p>Scholars study the transmission chain, narrators, wording, context, and relationship to stronger evidence.</p></div><div class="record"><span>Qur’anic foundation</span><strong>Verify consequential reports</strong><p>Qur’an 49:6 is commonly discussed as a foundation for carefully verifying reports.</p></div><div class="source-note">Production content should be reviewed by qualified Twelver Shia scholars. Classifications and legal implications may differ among scholars.</div>`:`<p class="sheet-intro">Evidence gathered while tracing a narration circulating through the market.</p>${Object.entries(clueData).map(([k,v],i)=>`<div class="record ${state.clues.has(k)?'':'locked'}"><span>Evidence ${i+1}</span><strong>${state.clues.has(k)?v.title:'Undiscovered'}</strong><p>${state.clues.has(k)?v.copy:'Use Scholar’s Focus in the street to find this clue.'}</p></div>`).join('')}<div class="source-note">A fictional narrative built around real verification principles. Do not use the game alone to authenticate a report.</div>`;$('#casebook').classList.remove('hidden')}
$('#beginBtn').onclick=()=>{$('#opening').classList.add('hidden');toast('Look toward the golden marker and press E')};$('#maryamMarker').onclick=openDialogue;$('#closeDialogue').onclick=closeDialogue;$('#focusBtn').onclick=()=>setFocus();$('#journalBtn').onclick=()=>openSheet('journal');$('#sourcesBtn').onclick=()=>openSheet('sources');$('#settingsBtn').onclick=()=>{toast('Mouse / arrows: look · Q: focus · E: speak · Esc: close')};$$('[data-close]').forEach(x=>x.onclick=()=>$('#casebook').classList.add('hidden'));$$('.clue').forEach(x=>x.onclick=()=>investigate(x.dataset.clue));
window.addEventListener('mousemove',e=>{if(!$('#dialogue').classList.contains('hidden')||!$('#opening').classList.contains('hidden'))return;state.lookX=(e.clientX/innerWidth-.5)*-2.2;state.lookY=(e.clientY/innerHeight-.5)*-1.5;$('#scene').style.setProperty('--look-x',`${state.lookX}%`);$('#scene').style.setProperty('--look-y',`${state.lookY}%`)});
window.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(k==='q')setFocus();if(k==='e'&&$('#opening').classList.contains('hidden'))openDialogue();if(e.key==='Escape'){closeDialogue();$('#casebook').classList.add('hidden')}if(['arrowleft','a'].includes(k))state.lookX=Math.min(2.5,state.lookX+.4);if(['arrowright','d'].includes(k))state.lookX=Math.max(-2.5,state.lookX-.4);if(['arrowup','w'].includes(k))state.lookY=Math.min(1.5,state.lookY+.3);if(['arrowdown','s'].includes(k))state.lookY=Math.max(-1.5,state.lookY-.3);$('#scene').style.setProperty('--look-x',`${state.lookX}%`);$('#scene').style.setProperty('--look-y',`${state.lookY}%`)});
sync();
